📝 New Blog - Announcing TinaCMS Version 2.0
tinacms/tina.io pull request #2111
Opened 2024-08-28 03:59 UTC by JackDevAU

### General Contributing:

- [ ] Have you followed the guidelines in our [Contributing document](https://github.com/tinacms/tina.io/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### All New Content Submissions: (To be confirmed by reviewer)

- [ ] Title is short & specific
- [ ] Headers are logically ordered & consistent
- [ ] Purpose of document is explained in the first paragraph
- [ ] Procedures are tested and work
- [ ] Any technical concepts are explained or linked to
- [ ] Document follows structure from templates
- [ ] All links work
- [ ] The spelling and grammar checker has been run
- [ ] Graphics and images are clear and useful
- [ ] Any prerequisites and next steps are defined.

2024-08-28 06:26 UTC, joshbermanssw commented on content/blog/version-2.mdx
should there be a space around the hyphen, ".... But that's not all—TinaCMS has ....."

2024-09-02 23:18 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development company and long-time Tina customer, this acquisition mar
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-03 06:28 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development company and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-03 06:41 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development company and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-03 06:45 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development company and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-05 00:52 UTC, bradystroud requested changes

2024-09-05 00:52 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-05 00:57 UTC, bradystroud requested changes

2024-09-05 00:57 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-05 02:51 UTC, bradystroud requested changes

2024-09-05 02:51 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development company and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-05 02:56 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development company and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-05 03:00 UTC, bradystroud commented on content/blog/version-2.mdx
> +We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software consultancy and long-time Tina customer, this acquisition marked a ne
```suggestion
We were very proud to announce that TinaCMS had officially become part of the SSW family. Acquired by SSW, an Australian software development company and long-time Tina customer, this acquisition marked a new chapter for TinaCMS. This partnership will allow us to further enhance our platform and continue delivering top-notch solutions to our community. Rest assured, there will be no disruptions to our service, and our commitment to innovation remains stronger than ever.
```

2024-09-05 05:54 UTC, landonmaxwell approved these changes
lgtm

2024-09-06 00:43 UTC, bradystroud commented
As per my conversation with @JackDevAU waiting for approval from some more people

2024-11-26 00:40 UTC, bradystroud commented
Merging because its been open for months, it probably wont have that much traffic and its easy to change if there are bugs.

2024-11-26 00:40 UTC, merged