✨ Key Features | Homepage Carousel and Cleanup
tinacms/tina.io pull request #2164
Opened 2024-09-06 13:00 UTC by joshbermanssw

This is a component I had built a while ago but was never finished due to needing media for it. However because it is so old and we have updated some of its dependent components/ methods i decided it'd be easier to re-build it. 

PBI https://github.com/tinacms/tina.io/issues/1805

Old PR https://github.com/tinacms/tina.io/pull/1816

This is a component built from @bettybondoc's original re-design of the homepage from figma: https://www.figma.com/design/Jyj0SszjfSBc6Minkl3g1l/Tina.io?node-id=399-5400&node-type=FRAME

**Changes:**
- added another button variant, ghost (blue) which is the same as ghost normal but blue text instead of red
- created new CarouselFeature component and template
- removed 2 old feature blocks from the homepage (as per figma design) 

**Still todo**
- [x] media rendering with using the `image` field rather than src

2024-09-17 07:28 UTC, isaaclombardssw requested changes
Sick component 🚀 

Only thing that has to change is the below (missing content in 1st and 3rd RHS option).

![2024-09-17_17-25-45](https://github.com/user-attachments/assets/ae4bde71-0493-4a08-8a8e-1c8abcd1275c)

2024-09-20 01:11 UTC, isaaclombardssw approved these changes
Code looks aight 👍

2024-09-20 01:11 UTC, isaaclombardssw commented on components/blocks/CarouselFeature.tsx
> +    };
Could do with some comments.

2024-09-20 01:13 UTC, joshbermanssw commented on components/blocks/CarouselFeature.tsx
> +};
done

2024-09-20 01:20 UTC, joshbermanssw commented on components/blocks/CarouselFeature.tsx
> +    };
done

2024-09-25 00:22 UTC, merged