💄✨ Add Co-Author field to Blog Posts
tinacms/tina.io pull request #2176
Opened 2024-09-11 02:33 UTC by joshbermanssw

As per #2107 we wanted to be able to acknowledge users when they are also 'checking' blog posts (as this can sometimes be a lengthy process 😅) 

**Changes:**
- [ ] Added a string list called co-Authors to the blog schema 
- [ ] Added the co-author field to the getExpandedBlogPosts gql query 
- [ ] Rendered the co-authors field on both the `page-index.tsx` file and `[slug].tsx` file for blogs 

<img width="1327" alt="Screenshot 2024-09-11 at 12 12 58 PM 1" src="https://github.com/user-attachments/assets/22755a89-566e-4623-b11c-a6d74518e9ab">
**Figure: 📄 Co-authors displayed on a blog post**

<img width="1314" alt="Screenshot 2024-09-11 at 12 28 35 PM" src="https://github.com/user-attachments/assets/705442a6-78e5-4774-a4f6-2093665d45c7">
**Figure: 📄 Co-authors displayed on minimised blog post /blog page**

2024-09-11 03:08 UTC, bradystroud requested changes

2024-09-11 03:08 UTC, bradystroud commented on content/blog/TinaCMS-sponsoring-the-Copenhagen-Developers-Festival.mdx
> +coAuthors:
Coauthors is one word, sometimes hypenated

```suggestion
coauthors:
```

or 

```suggestion
co_authors:
```

2024-09-11 03:08 UTC, bradystroud commented on tina/collectionsSchema/blogs.tsx
> +      name: 'coAuthors',
same as above

2024-09-11 03:08 UTC, bradystroud commented on tina/queries/post.gql
> +    coAuthors
same as above

2024-09-16 05:49 UTC, joshbermanssw commented
awaiting designer

2024-11-19 22:12 UTC, closed without merging