📑 GitHub Co-Authoring
tinacms/tina.io pull request #2648
Opened 2024-12-20 05:10 UTC by joshbermanssw

cc: @bradystroud @JackDevAU @adamcogan @wicksipedia 

📧 Tina - improve co-authoring

This PR creates a new document running users through the powers and perks of the Git Co-Authoring tool when using TinaCMS

2024-12-20 05:45 UTC, edkranz approved these changes

2024-12-21 21:00 UTC, bradystroud requested changes
There is a section in the FAQ that talks about co-authoring. It should link to this page

2024-12-29 23:28 UTC, JackDevAU commented on content/docs/tina-cloud/git-co-authoring.mdx
> +Co-authoring is a feature that combines the user’s identity with the tina-cloud-app entity in GitHub commit logs. This ensures that when users commit changes to their TinaCMS projects, both their Git
```suggestion
Co-authoring is a feature that combines the user’s identity with the tina-cloud-app entity in GitHub commit logs. This ensures that when users commit changes to their TinaCMS projects, both their GitHub account and the tina-cloud-app entity are listed as co-authors. When a user with Co-Authoring enabled makes content edits through TinaCMS, the corresponding Git changes are marked as “Co-authored by tina-cloud-app.”
```

2024-12-29 23:30 UTC, JackDevAU commented on content/docs/tina-cloud/git-co-authoring.mdx
> +![](</img/Screenshot 2024-12-20 at 3.42.33 pm.png>)**Figure: ❌ Bad Example - Who made this change?**
Image doesn't seem to be working

2024-12-29 23:30 UTC, JackDevAU commented on content/docs/tina-cloud/git-co-authoring.mdx
> +![](</img/Screenshot 2024-12-20 at 3.43.10 pm.png>)**Figure: ✅ Good Example - I can track down Ben Neoh about this change**
Image doesn't seem to be working

2025-01-02 22:45 UTC, joshbermanssw commented
Closing - opened a new one. https://github.com/tinacms/tina.io/pull/2679

2025-01-02 22:45 UTC, closed without merging